title: Applied Population Dynamics
author: Richard Chandler
email: rchandler@warnell.uga.edu
description: A course on population ecology and wildlife conservation
theme: minima
header_pages:
  - syllabus.md
  - labs/labs.md
  - lectures/lectures.md

