---
format: html
---


**Applied Population Dynamics**\n
WILD 5700/5700L, 7700/7700L, Fall 2025\n
Lecture: Mon, Wed 9:55--10:50 AM; Room 1-304\n
Lab: Wed 2:55--5:35; Room 1-304\n

+:--------------+:-------------------------:+:-:+:------------------:+:------------------:+
|               | **Instructor**            |   | **Teaching Assistants**                 |
+---------------+---------------------------+---+--------------------+--------------------+
|               | Dr. Richard Chandler      |   | Urvi Gupta         | Katherine          |
|               |                           |   |                    | Araúz-Ponce        |
+---------------+---------------------------+---+--------------------+--------------------+
| Office room:  | 3-407                     |   | 3-402              | 3-402              |
+---------------+---------------------------+---+--------------------+--------------------+
| Email:        | rchandler@warnell.uga.edu |   | urvi.gupta@uga.edu | arauzponce@uga.edu |
+---------------+---------------------------+---+--------------------+--------------------+
| Office hours: | Mon 11:00--12:00          |   | Mon 2:30--3:30     | Thur 11:00--12:00  |
+---------------+---------------------------+---+--------------------+--------------------+
|               | or by appointment         |   |                    |                    |
+---------------+---------------------------+---+--------------------+--------------------+

# Course Description {#course-description .unnumbered}

Foundations of population dynamics from an applied perspective.
Exponential and logistic population growth, life tables, species
interactions, and stochastic models for structured populations. Sampling
design and analytical methods for estimating abundance and demographic
parameters. Application of population models to harvest management and
conversation of small populations. Integrative student project required.

# Course Objectives and Learning Outcomes {#course-objectives-and-learning-outcomes .unnumbered}

This course will present the theory necessary for understanding wildlife
population dynamics, and it will explain how to use theory and data to
inform management and conservation efforts. By the end of the course,
students will be able to: (1) Develop models to forecast the impacts of
environmental change and management actions on wildlife populations; (2)
Design field studies to collect data on wildlife demographics; (3) Use
statistical software to analyze data on wildlife populations; (4) Review
scientific literature to support modeling decisions; (5) Present
modeling results in a short scientific paper and an oral presentation.

# Tips for Success {#tips-for-success .unnumbered}

- Take notes on printed handouts

- Don't bring laptops or tablets to lecture

- Review notes before each lecture

- Keep up with assigned readings

- Finish lab assignments during lab

- Ask questions during lecture and lab.

- Start the final project early.

- Visit with the TAs and me during office hours.

# Grading {#grading .unnumbered}

::: center
                          Quantity   Grade percentage$^*$
  --------------------- ---------- ----------------------
  Quizzes                       10                    10%
  Lab assignments               14                    35%
  Final paper$^{**}$             1                    20%
  Exams                          3                    30%
  Class participation                                  5%

\
$^*$Late assignments will be penalized 3 points/day, up to a maximum of
50 points off.\
$^{**}$Graduate students will analyze a real dataset and summarize the
results in their final paper.\
A = 93--100, A- = 90--92, B+ = 87--89, B = 83--86, B- = 80--82,\
C+ = 77--79, C = 73--76, C-= 70--72, D = 60--69, F =
$<$`<!-- -->`{=html}60.
:::

# Textbook {#textbook .unnumbered}

Conroy, M.J. and J.P. Carroll. 2009. Quantitative Conservation of
Vertebrates. Wiley-Blackwell. [Digital
copies](http://preproxy.galib.uga.edu/login?url=http://onlinelibrary.wiley.com/book/10.1002/9781444303155)
are available for free through the UGA library.

# Prerequisites {#prerequisites .unnumbered}

  ------------- --------------------------------------------------------
  Undergrads:   (MATH 1113 or MATH 1113E) and (FANR 3200 or FANR 3200W
                or ECOL 3500-3500L or ECOL 3505H-3505L)

  Grads:        FANR 6750-6750D or BIOS 7010 or BIOS 7010E
  ------------- --------------------------------------------------------

# Academic Honesty {#academic-honesty .unnumbered}

UGA Student Honor code: "I will be academically honest in all of my
academic work and will not tolerate academic dishonesty of others." A
Culture of Honesty, the University's policy and procedures for handling
cases of suspected dishonesty, can be found at
<https://honesty.uga.edu/>. You are responsible for informing yourself
about the university's standards before performing any academic work.
Lack of knowledge of the academic honesty policy is not a reasonable
explanation for a violation. Please ask if you have questions related to
course assignments and the academic honesty policy. Any form of possible
academic dishonesty will be reported to the UGA Office of the Vice
President for Instruction.

# Format and Attendance {#format-and-attendance .unnumbered}

Lectures and labs will be in-person. Attendance will not be recorded,
but it will be impossible to succeed in the class if you don't
participate in lectures and labs. Quizzes will be taken during lectures.

# Cell Phones and Laptops {#cell-phones-and-laptops .unnumbered}

Cell phones are not allowed during class unless explicit permission is
granted. Laptop computers are discouraged during lecture, but you should
bring laptops to labs.

# UGA Well-Being Resources {#uga-well-being-resources .unnumbered}

UGA Well-being Resources promote student success by cultivating a
culture that supports a more active, healthy, and engaged student
community. Anyone needing assistance is encouraged to contact Student
Care & Outreach (SCO) in the Division of Student Affairs at 706-542-8479
or visit [sco.uga.edu](sco.uga.edu){.uri}. Student Care & Outreach helps
students navigate difficult circumstances by connecting them with the
most appropriate resources or services. They also administer the
Embark@UGA program which supports students experiencing, or who have
experienced, homelessness, foster care, or housing insecurity.

UGA provides both clinical and non-clinical options to support student
well-being and mental health, any time, any place. Whether on campus, or
studying from home or abroad, UGA Well-being Resources are here to help.

University Health Center:
[healthcenter.uga.edu](healthcenter.uga.edu){.uri}\
Counseling and Psychiatric Services: [caps.uga.edu](caps.uga.edu){.uri}
or 24/7 crisis support at 706-542-2273\
Health Promotion/ Fontaine Center:
[healthpromotion.uga.edu](healthpromotion.uga.edu){.uri}\
Accessibility and Testing:
[accessibility.uga.edu](accessibility.uga.edu){.uri}\
Additional information, including free digital well-being resources, can
be accessed through the UGA app or by visiting
<https://well-being.uga.edu>.

# Academic Coaching {#academic-coaching .unnumbered}

For assistance with time management, test and performance anxiety,
notetaking, motivation, text comprehension, test preparation, and other
barriers to success at UGA, visit the [Office of Academic
Enhancement](https://dae.uga.edu/services/academic-coaching/).

# Accommodations for Disabilities {#accommodations-for-disabilities .unnumbered}

If you require a disability-required accommodation, it is essential that
you register with the Disability Resource Center (<https://drc.uga.edu>;
706-542-8719) and notify me of your eligibility for reasonable
accommodations. We can then plan how best to coordinate your
accommodations. Please note that accommodations cannot be provided
retroactively.

# Generative AI {#generative-ai .unnumbered}

Artificial intelligence (AI) tools, like chatGPT, are generally not
allowed in this course. All work submitted must be your own, and it must
make use of the concepts and tools that we covered in class, rather than
content generated by AI. The only acceptable use of AI is editing, as
opposed to creation. If you would like to use AI to edit your writing or
your code, you must disclose (1) the prompts provided to AI, (2) your
original text or code, and (3) your final text or code. Prompts and
output can be disclosed by copying and pasting screenshots into
assignment documents. Failure to disclose this information will be
considered a violation of the UGA Student Honor Code.

More on AI:

- [Under the AI hood](https://thebullshitmachines.com/)

- [AI teaching-learning
  circle](https://drive.google.com/file/d/1AN9GrksC4kLIE57fuS4zg8nPsyYtNEmr/view?usp=sharing)

# Tentative Course Outline {#tentative-course-outline .unnumbered}

::: center
+----------+-----------------------------+-----------------------------+
| **Date** | **Lecture**                 | **Lab**                     |
+:=========+:============================+:============================+
| PART I -- Models                                                     |
+----------+-----------------------------+-----------------------------+
| Aug 17   | Introduction                |                             |
+----------+-----------------------------+-----------------------------+
| Aug 19   | BIDE model                  | Excel and R basics          |
+----------+-----------------------------+-----------------------------+
| Aug 24   | Exponential and geometric   |                             |
|          | growth                      |                             |
+----------+-----------------------------+-----------------------------+
| Aug 26   | Logistic growth             | Geometric and logistic      |
|          |                             | growth                      |
+----------+-----------------------------+-----------------------------+
| Aug 31   | Harvest models              |                             |
+----------+-----------------------------+-----------------------------+
| Sept 2   | Stochasticity               | Harvest models              |
+----------+-----------------------------+-----------------------------+
| Sept 7   | Labor Day -- no lecture     |                             |
+----------+-----------------------------+-----------------------------+
| Sept 9   | Extinction risk             | Extinction risk             |
+----------+-----------------------------+-----------------------------+
| Sept 14  | Extinction risk             |                             |
+----------+-----------------------------+-----------------------------+
| Sept 16  | Exam I                      | Data collection             |
+----------+-----------------------------+-----------------------------+
| Sept 21  | Competition and predation   |                             |
+----------+-----------------------------+-----------------------------+
| Sept 23  | Competition and predation   | Competition and predation   |
+----------+-----------------------------+-----------------------------+
| Sept 28  | Age structure               |                             |
+----------+-----------------------------+-----------------------------+
| Sept 30  | Stage structure             | Age/stage structure         |
+----------+-----------------------------+-----------------------------+
| Oct 5    | Source-sink dynamics        |                             |
+----------+-----------------------------+-----------------------------+
| Oct 7    | Metapopulations             | Metapopulations             |
+----------+-----------------------------+-----------------------------+
| Oct 12   | Population viability        |                             |
|          | analysis                    |                             |
+----------+-----------------------------+-----------------------------+
| Oct 14   | Sensitivity analysis        | Population viability        |
|          |                             | analysis                    |
+----------+-----------------------------+-----------------------------+
| PART II -- Estimation                                                |
+----------+-----------------------------+-----------------------------+
| Oct 19   | Study design                |                             |
+----------+-----------------------------+-----------------------------+
| Oct 21   | Exam II                     | Data collection             |
+----------+-----------------------------+-----------------------------+
| Oct 26   | Occupancy models            |                             |
+----------+-----------------------------+-----------------------------+
| Oct 28   | Occupancy models            | Occupancy models            |
+----------+-----------------------------+-----------------------------+
| Nov 2    | Distance sampling           | Due: First draft            |
+----------+-----------------------------+-----------------------------+
| Nov 4    | Distance sampling           | Distance sampling           |
+----------+-----------------------------+-----------------------------+
| Nov 9    | Mark-recapture: closed      |                             |
|          | populations                 |                             |
+----------+-----------------------------+-----------------------------+
| Nov 11   | Mark-recapture: closed      | Mark-recapture I            |
|          | populations                 |                             |
+----------+-----------------------------+-----------------------------+
| Nov 16   | Mark-recapture: open        | Due: peer review            |
|          | populations                 |                             |
+----------+-----------------------------+-----------------------------+
| Nov 18   | Mark-recapture: open        | Mark-recapture II           |
|          | populations                 |                             |
+----------+-----------------------------+-----------------------------+
| Nov 23   | Thanksgiving Break          | Thanksgiving Break          |
+----------+-----------------------------+-----------------------------+
| Nov 25   | Thanksgiving Break          | Thanksgiving Break          |
+----------+-----------------------------+-----------------------------+
| Nov 30   | Survival analysis           |                             |
+----------+-----------------------------+-----------------------------+
| Dec 2    | Reading day                 | No lab                      |
+----------+-----------------------------+-----------------------------+
| Dec 9    | Final exam (8:00-11:00am)   | Room 1-304                  |
+----------+-----------------------------+-----------------------------+
:::

The course syllabus is a general plan for the course; deviations
announced to the class by the instructor may be necessary.
