---
title: Applied Population Dynamics
author:
  name: Richard Chandler
  affiliation:
    name: Warnell School of Forestry and Natural Resources\nUniversity of Georgia
format: html
---

## Course Description

Foundations of population dynamics from an applied
perspective. Exponential and logistic population growth, life tables,
species interactions, and stochastic models for structured
populations. Sampling design and analytical methods for estimating
abundance and demographic parameters. Application of population models
to harvest management and conversation of small
populations. Integrative student project required.  

## Course Objectives and Learning Outcomes

This course will present the theory necessary for understanding
wildlife population dynamics, and it will explain how to use theory
and data to inform management and conservation efforts. By the end of
the course, students will be able to: (1) Develop models to forecast
the impacts of environmental change and management actions on wildlife
populations; (2) Design field studies to collect data on wildlife
demographics; (3) Use statistical software to analyze data on wildlife
populations; (4) Review scientific literature to support modeling
decisions; (5) Present modeling results in a short scientific paper
and an oral presentation.


## Course materials

### Week 1 - Introduction and the BIDE model

- [Lecture 1 - Introduction](lectures/intro/lecture-intro.qmd)

- [Lecture 2 - BIDE model](lectures/BIDE/lecture-BIDE.qmd)

- [Lab 1 - Excel and R Basics](labs/intro/lab-Excel-R-Basics.qmd)

### Week 2 - Geometric and logistic growth

- Lecture 3

