\documentclass[12pt]{article}\usepackage[]{graphicx}\usepackage[]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlsng}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hldef}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}

%\usepackage[roman]{../pres1}
%\usepackage[sans]{../pres1}

\usepackage[hmargin=1in,vmargin=1in]{geometry}
\usepackage{parskip}
\usepackage{hyperref}
\usepackage{graphicx}
\usepackage{color}
\hypersetup{pdfstartview=FitV,hidelinks}




\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}

{
  \Large
  \centering
  Lab Assignment --- Occupancy Models in R \\
  Due by noon on Monday \par
}

\vspace{10pt}


Answer each of the following questions, and submit your answers by 
uploading a single \textcolor{red}{WORD} file to ELC. Unlike previous labs,
copy and paste code and results from R to the WORD file. You should
also copy and paste entire screenshots to show the relevant output. If
you know how to use RMarkdown, please do so. Name the file something
like \texttt{Chandler-lab.docx}.


%\vspace{12pt}


\section*{\normalsize Preliminaries: Occupancy models using the R
package `unmarked'}


Occupancy models can be fit using the `unmarked' package in {\tt
R}. To install `unmarked', issue this command in R or RStudio: 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{install.packages}\hldef{(}\hlsng{"unmarked"}\hldef{)}
\end{alltt}
\end{kframe}
\end{knitrout}

Once it's installed, you need to load it:

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{library}\hldef{(unmarked)}
\end{alltt}
\end{kframe}
\end{knitrout}



\subsection*{\normalsize Getting Data into R}
\vspace{-10pt}


Now we're ready to import the data. For exercise I, you will import
the file named \\ \texttt{quail-data-for-R.csv}. For exercise II, you
will import the file \texttt{dipnet-data-for-R.csv}. Before you import
those files, here is some general guidance on importing data, followed
by occupancy modeling examples.


The easiest way to import data into R is to save the data as a
\texttt{.csv} file, which has been done for you already, and put it in
your working directory. The working directory is the location on your
computer where R will look for files by default. To find out
where the working directory is, do this:  
    
\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{getwd}\hldef{()}
\end{alltt}
\begin{verbatim}
## [1] "/home/richard/courses/applied-popdy/labs/occupancy-modeling"
\end{verbatim}
\end{kframe}
\end{knitrout}

If that is the location where your data are, you're ready to
import. Otherwise, you need to change your working directory to the
location where your data files are located. You can change your
working directory using the drop-down menu options
(\texttt{Session > Set Working Directory}), or using a command
like this: 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{## You will need to modify the path in quotes}
\hlkwd{setwd}\hldef{(}\hlsng{"C:/Users/Richard/Documents/APD/"}\hldef{)}
\end{alltt}
\end{kframe}
\end{knitrout}

Once your working directory is correctly specified, you can import the
data using this command: 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{exampleData} \hlkwb{<-} \hlkwd{read.csv}\hldef{(}\hlsng{"example-data.csv"}\hldef{)}
\end{alltt}
\end{kframe}
\end{knitrout}

\newpage
Let's look at a summary:

\begin{knitrout}\scriptsize
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{summary}\hldef{(exampleData)}
\end{alltt}
\begin{verbatim}
##       Site       season1visit1 season1visit2   season2visit1 season2visit2   habitatIndex  
##  Min.   : 1.00   Min.   :0.0   Min.   :0.000   Min.   :0.0   Min.   :0.00   Min.   :1.040  
##  1st Qu.:10.75   1st Qu.:0.0   1st Qu.:0.000   1st Qu.:0.0   1st Qu.:0.00   1st Qu.:1.885  
##  Median :20.50   Median :0.0   Median :0.000   Median :0.0   Median :0.00   Median :2.805  
##  Mean   :20.50   Mean   :0.4   Mean   :0.325   Mean   :0.3   Mean   :0.25   Mean   :2.912  
##  3rd Qu.:30.25   3rd Qu.:1.0   3rd Qu.:1.000   3rd Qu.:1.0   3rd Qu.:0.25   3rd Qu.:3.835  
##  Max.   :40.00   Max.   :1.0   Max.   :1.000   Max.   :1.0   Max.   :1.00   Max.   :4.740
\end{verbatim}
\end{kframe}
\end{knitrout}

Columns 2-4 have the occupancy data. The fifth column has a
site-specific covariate. Before we can run a single-season occupancy
model, we have to format the data.




\subsection*{Example: Formatting data for single-season analysis in unmarked}


The example dataset is from a study with 2 seasons, but we'll begin by
pretending that it is from a single-season study with 4 surveys at
each site. 


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{## First, extract columns 2-4 with the occupancy data}
\hldef{occData} \hlkwb{<-} \hldef{exampleData[,}\hlkwd{c}\hldef{(}\hlsng{"season1visit1"}\hldef{,} \hlsng{"season1visit2"}\hldef{,}
                          \hlsng{"season2visit1"}\hldef{,} \hlsng{"season2visit2"}\hldef{)]}
\hlcom{## Next, extract the column with the site covariate.}
\hlcom{## It must be formatted as a data.frame}
\hldef{habIndex} \hlkwb{<-} \hldef{exampleData[,}\hlsng{"habitatIndex"}\hldef{,}\hlkwc{drop}\hldef{=}\hlnum{FALSE}\hldef{]}
\hlcom{## Finally, put the pieces together}
\hldef{umf} \hlkwb{<-} \hlkwd{unmarkedFrameOccu}\hldef{(}\hlkwc{y}\hldef{=occData,} \hlkwc{siteCovs}\hldef{=habIndex)}
\end{alltt}
\end{kframe}
\end{knitrout}


Now that we have the data formatted, we should summarize it again to
make sure everything looks good: 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{summary}\hldef{(umf)}
\end{alltt}
\begin{verbatim}
## unmarkedFrame Object
## 
## 40 sites
## Maximum number of observations per site: 4 
## Mean number of observations per site: 4 
## Sites with at least one detection: 22 
## 
## Tabulation of y observations:
##   0   1 
## 109  51 
## 
## Site-level covariates:
##   habitatIndex  
##  Min.   :1.040  
##  1st Qu.:1.885  
##  Median :2.805  
##  Mean   :2.912  
##  3rd Qu.:3.835  
##  Max.   :4.740
\end{verbatim}
\end{kframe}
\end{knitrout}

All is well. Let's fit some models. 



\subsection*{Example: Fitting single-season occupancy models}

Model fitting is the process of fitting a model to the data. In other
words, it's the process of estimating the parameters of a model using
a dataset. 

We will fit two models using the \texttt{occu} function. In the first
model, there are no covariates, meaning that occupancy probability
($\psi$) and detection probability ($p$) are constant. We will call
this the null model: 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{nullModel} \hlkwb{<-} \hlkwd{occu}\hldef{(}\hlopt{~}\hlnum{1} \hlopt{~}\hlnum{1}\hldef{, umf)}
\end{alltt}
\end{kframe}
\end{knitrout}

The line of code above fits the single-season model to the data. The
first argument is a formula 
describing the model that you want to fit. If it is \verb+~1 ~1+, then
there are no covariates. If there are covariates, the detection
probability covariates go after the first \verb+~+ and the occupancy
covariates go after the second \verb+~+. We will add covariates
later. First, let's summarize the results: 


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{summary}\hldef{(nullModel)}
\end{alltt}
\begin{verbatim}
## 
## Call:
## occu(formula = ~1 ~ 1, data = umf)
## 
## Occupancy (logit-scale):
##  Estimate    SE     z P(>|z|)
##      0.29 0.338 0.858   0.391
## 
## Detection (logit-scale):
##  Estimate    SE     z P(>|z|)
##      0.23 0.235 0.977   0.328
## 
## AIC: 177.2621 
## Number of sites: 40
## optim convergence code: 0
## optim iterations: 19 
## Bootstrap iterations: 0
\end{verbatim}
\end{kframe}
\end{knitrout}

Notice that the parameters are estimated on the logit-scale. To get
estimates on the probability scale, we need to back-transform them. If
there are no covariates, we can back-transform like this: 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlcom{## Occupancy estimate - Pr(site is occupied)}
\hlkwd{backTransform}\hldef{(nullModel,} \hlkwc{type}\hldef{=}\hlsng{"state"}\hldef{)}
\end{alltt}
\begin{verbatim}
## Backtransformed linear combination(s) of Occupancy estimate(s)
## 
##  Estimate     SE LinComb (Intercept)
##     0.572 0.0827    0.29           1
## 
## Transformation: logistic
\end{verbatim}
\begin{alltt}
\hlcom{## Detection estimate - Pr(detection | site is occupied)}
\hlkwd{backTransform}\hldef{(nullModel,} \hlkwc{type}\hldef{=}\hlsng{"det"}\hldef{)}
\end{alltt}
\begin{verbatim}
## Backtransformed linear combination(s) of Detection estimate(s)
## 
##  Estimate     SE LinComb (Intercept)
##     0.557 0.0581    0.23           1
## 
## Transformation: logistic
\end{verbatim}
\end{kframe}
\end{knitrout}

We conclude that the probability that a site is occupied is 0.572. The
probability that the species is detected (on a single visit), if the
site is occupied, is 0.557. These two estimates are similar, but that
is just a coincidence.

Let's now assess the possibility that occupancy probability depends on
the habitat index. We can fit such a model like this: 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{detNullOccHab} \hlkwb{<-} \hlkwd{occu}\hldef{(}\hlopt{~}\hlnum{1} \hlopt{~}\hldef{habitatIndex, umf)}
\end{alltt}
\end{kframe}
\end{knitrout}

The summary indicates that habitat effect is positive, indicating that
occupancy probability increases as the index increases.  

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{summary}\hldef{(detNullOccHab)}
\end{alltt}
\begin{verbatim}
## 
## Call:
## occu(formula = ~1 ~ habitatIndex, data = umf)
## 
## Occupancy (logit-scale):
##              Estimate    SE     z P(>|z|)
## (Intercept)    -1.768 1.017 -1.74  0.0820
## habitatIndex    0.723 0.348  2.08  0.0378
## 
## Detection (logit-scale):
##  Estimate    SE     z P(>|z|)
##      0.23 0.235 0.979   0.327
## 
## AIC: 174.192 
## Number of sites: 40
## optim convergence code: 0
## optim iterations: 20 
## Bootstrap iterations: 0
\end{verbatim}
\end{kframe}
\end{knitrout}


To visualize the habitat effect, we need to predict occupancy at
several values of the habitat index, which ranged in value from
approximately 1-5. We can create a sequence of values and put it into
a data frame for prediction like this: 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{predData} \hlkwb{<-} \hlkwd{data.frame}\hldef{(}\hlkwc{habitatIndex}\hldef{=}\hlkwd{seq}\hldef{(}\hlkwc{from}\hldef{=}\hlnum{1}\hldef{,} \hlkwc{to}\hldef{=}\hlnum{5}\hldef{,} \hlkwc{length.out}\hldef{=}\hlnum{10}\hldef{))}
\end{alltt}
\end{kframe}
\end{knitrout}

Now, let's do the prediction:

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{predOcc} \hlkwb{<-} \hlkwd{predict}\hldef{(detNullOccHab,} \hlkwc{newdata}\hldef{=predData,}
                   \hlkwc{type}\hldef{=}\hlsng{"state"}\hldef{,} \hlkwc{append}\hldef{=}\hlnum{TRUE}\hldef{)}
\hldef{predOcc}
\end{alltt}
\begin{verbatim}
##    Predicted         SE      lower     upper habitatIndex
## 1  0.2601584 0.13530441 0.08144029 0.5824030     1.000000
## 2  0.3265380 0.12675690 0.13544954 0.6000900     1.444444
## 3  0.4006819 0.11216471 0.21113434 0.6254747     1.888889
## 4  0.4796701 0.09729524 0.30039695 0.6643364     2.333333
## 5  0.5596880 0.09008114 0.38307019 0.7223861     2.777778
## 6  0.6367200 0.09342213 0.44264168 0.7945805     3.222222
## 7  0.7073227 0.10152150 0.48032215 0.8633721     3.666667
## 8  0.7691782 0.10736889 0.50459780 0.9159817     4.111111
## 9  0.8212643 0.10774837 0.52155057 0.9509032     4.555556
## 10 0.8636800 0.10262384 0.53440045 0.9722013     5.000000
\end{verbatim}
\end{kframe}
\end{knitrout}

The ``Predicted'' values are the estimates of occupancy for each value
of ``habitatIndex''. Standard errors and 95\% confidence intervals are
also returned. 

Here's how to visualize the predictions with the confidence intervals: 

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{plot}\hldef{(Predicted} \hlopt{~} \hldef{habitatIndex,} \hlkwc{data}\hldef{=predOcc,} \hlkwc{type}\hldef{=}\hlsng{"l"}\hldef{,} \hlkwc{ylim}\hldef{=}\hlkwd{c}\hldef{(}\hlnum{0}\hldef{,}\hlnum{1}\hldef{),}
     \hlkwc{xlab}\hldef{=}\hlsng{"Habitat index"}\hldef{,} \hlkwc{ylab}\hldef{=}\hlsng{"Occupancy"}\hldef{)}
\hlkwd{lines}\hldef{(lower} \hlopt{~} \hldef{habitatIndex,} \hlkwc{data}\hldef{=predOcc,} \hlkwc{lty}\hldef{=}\hlnum{2}\hldef{)}
\hlkwd{lines}\hldef{(upper} \hlopt{~} \hldef{habitatIndex,} \hlkwc{data}\hldef{=predOcc,} \hlkwc{lty}\hldef{=}\hlnum{2}\hldef{)}
\end{alltt}
\end{kframe}

{\centering \includegraphics[width=0.8\linewidth]{figure/plotOcc-1} 

}


\end{knitrout}



\subsection*{Example: Fitting multi-season occupancy models}


We will use different functions to format the data and fit the
multi-season occupancy models. Instead of using
\texttt{unmarkedFrameOccu}, we will use
\texttt{unmarkedMultFrame}. The number of seasons must be specified
using the \texttt{numPrimary} argument.


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{umfMS} \hlkwb{<-} \hlkwd{unmarkedMultFrame}\hldef{(}\hlkwc{y}\hldef{=occData,} \hlkwc{numPrimary}\hldef{=}\hlnum{2}\hldef{)}
\end{alltt}
\end{kframe}
\end{knitrout}

Let's take a look.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{summary}\hldef{(umfMS)}
\end{alltt}
\begin{verbatim}
## unmarkedFrame Object
## 
## 40 sites
## Maximum number of observations per site: 4 
## Mean number of observations per site: 4 
## Number of primary survey periods: 2 
## Number of secondary survey periods: 2 
## Sites with at least one detection: 22 
## 
## Tabulation of y observations:
##   0   1 
## 109  51
\end{verbatim}
\end{kframe}
\end{knitrout}

Model fitting is done using the \texttt{colext} function instead of
the \texttt{occu} function. Notice that the formulas have spaces
between them, unlike before.


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hldef{nullModelMS} \hlkwb{<-} \hlkwd{colext}\hldef{(}\hlopt{~}\hlnum{1}\hldef{,} \hlopt{~}\hlnum{1}\hldef{,} \hlopt{~}\hlnum{1}\hldef{,} \hlopt{~}\hlnum{1}\hldef{, umfMS)}
\end{alltt}
\end{kframe}
\end{knitrout}

Here are the results:

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{summary}\hldef{(nullModelMS)}
\end{alltt}
\begin{verbatim}
## 
## Call:
## colext(psiformula = ~1, gammaformula = ~1, epsilonformula = ~1, 
##     pformula = ~1, data = umfMS)
## 
## Initial (logit-scale):
##  Estimate    SE     z P(>|z|)
##     0.207 0.401 0.516   0.606
## 
## Colonization (logit-scale):
##  Estimate   SE     z P(>|z|)
##     -2.77 2.29 -1.21   0.226
## 
## Extinction (logit-scale):
##  Estimate    SE     z P(>|z|)
##     -1.35 0.828 -1.63   0.103
## 
## Detection (logit-scale):
##  Estimate    SE    z P(>|z|)
##     0.522 0.339 1.54   0.124
## 
## AIC: 178.8842 
## Number of sites: 40
## optim convergence code: 0
## optim iterations: 34 
## Bootstrap iterations: 0
\end{verbatim}
\end{kframe}
\end{knitrout}

We can back-transform and predict as before, but \texttt{type} should
be one of: ``psi'', ``col'', ``ext'', or ``det''.

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlkwd{backTransform}\hldef{(nullModelMS,} \hlkwc{type}\hldef{=}\hlsng{"psi"}\hldef{)}
\end{alltt}
\begin{verbatim}
## Backtransformed linear combination(s) of Initial estimate(s)
## 
##  Estimate     SE LinComb (Intercept)
##     0.551 0.0991   0.207           1
## 
## Transformation: logistic
\end{verbatim}
\begin{alltt}
\hlkwd{backTransform}\hldef{(nullModelMS,} \hlkwc{type}\hldef{=}\hlsng{"col"}\hldef{)}
\end{alltt}
\begin{verbatim}
## Backtransformed linear combination(s) of Colonization estimate(s)
## 
##  Estimate    SE LinComb (Intercept)
##    0.0588 0.127   -2.77           1
## 
## Transformation: logistic
\end{verbatim}
\begin{alltt}
\hlkwd{backTransform}\hldef{(nullModelMS,} \hlkwc{type}\hldef{=}\hlsng{"ext"}\hldef{)}
\end{alltt}
\begin{verbatim}
## Backtransformed linear combination(s) of Extinction estimate(s)
## 
##  Estimate    SE LinComb (Intercept)
##     0.206 0.135   -1.35           1
## 
## Transformation: logistic
\end{verbatim}
\begin{alltt}
\hlkwd{backTransform}\hldef{(nullModelMS,} \hlkwc{type}\hldef{=}\hlsng{"det"}\hldef{)}
\end{alltt}
\begin{verbatim}
## Backtransformed linear combination(s) of Detection estimate(s)
## 
##  Estimate     SE LinComb (Intercept)
##     0.628 0.0792   0.522           1
## 
## Transformation: logistic
\end{verbatim}
\end{kframe}
\end{knitrout}

The occupancy estimate is associated with the first season. 




\clearpage

\section*{Exercise I: Single-season models}

Suppose we are interested in estimating occupancy of bobwhite quail
({\it Colinus virginianus}) in abandoned ag fields. We randomly select
50 sites and survey them 4 times each in May. The resulting data indicate
whether at least one quail was detected at each site on each visit.    

In addition, you think there is a possibility that vegetation height
affects both occupancy and detection probability so you measure
average vegetation height at each site. Vegetation height will be the
covariate used in the analysis. 

Import the file {\tt quail-data-for-R.csv}.

\begin{enumerate}
  \item[(a)] Fit the single-season null model using the \texttt{occu} 
    function. Report the estimates and standard errors for psi
    ($\psi$) and p (on the probability scale). Interpret 
    these estimates (ie, what are the definitions of $\psi$ and p in this
    context?). 
  \item[(b)] Now run another model using \texttt{veght} as a
    predictor variable (covariate) for {\bf both} occupancy and detection
    probability. 
  \item[(c)] Is this model better than the first, based on AIC? The
    lower the AIC, the better the model's predictive performance.\footnote{$\mathrm{AIC} =
      -2\times \mathrm{log(likelihood)} + 2\times \mathrm{nParameters}$. AIC
      favors models that explain a lot of variation in the data using
      a small number of parameters.}  
  \item[(d)] Use the occupancy estimates (on the logit scale) to
    create a plot of the relationship between occurrence probability
    and vegetation height. Do this using the \texttt{predict} function
    as described above. Add the graph to your Word document.
  \item[(e)] Write one sentence to summarize the results displayed in the graph. 
\end{enumerate}

\clearpage

\section*{Exercise II: Multi-season model}

Use the southern two-lined salamander ({\it Eurycea cirrigera})
data from the past few years to do the following. Note: I pooled the
data from the 5 swipes of each team.

Begin by importing the file \texttt{dipnet-data-for-R.csv}.

\begin{enumerate}
  \item[(a)] Use the \texttt{colext} function to fit the null
    multi-season occupancy model. Report the estimates and standard
    errors for psi ($\psi$), gamma ($\gamma$), epsilon ($\epsilon$),
    and p on the probability scale. Report these values in a table in
    your Word document.   
  \item[(b)] Provide clear interpretations of the estimates. 
  \item[(c)] Based on these estimates, is there any reason to believe
    that occupancy has decreased over these years? Explain. 
  \item[(d)] How certain are you of these conclusions? Answer by
    describing how well you think our study design met the assumptions
    of the multi-season occupancy model. 
\end{enumerate}



\end{document}




